"""initial control schema

Revision ID: 4f36847b8351
Revises: 
Create Date: 2026-09-14 01:59:45.421844

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4f36847b8351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_capacity',
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('max_running', sa.Integer(), nullable=False),
    sa.CheckConstraint("scope_type IN ('global','datasource','user')", name='execution_capacity_scope_type_check'),
    sa.CheckConstraint('max_running > 0', name='execution_capacity_max_running_check'),
    sa.PrimaryKeyConstraint('scope_type', 'scope_id')
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key', 'version', name='metric_definitions_key')
    )
    op.create_table('policy_state',
    sa.Column('singleton', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('singleton', name='policy_state_singleton_check'),
    sa.PrimaryKeyConstraint('singleton')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resource_kind', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_resource', 'task_events', ['resource_kind', 'resource_id', 'id'], unique=False)
    op.create_table('task_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fencing_token', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("kind IN ('query','analysis','ingestion')", name='task_queue_kind_check'),
    sa.CheckConstraint("state IN ('READY','LEASED','DONE','FAILED')", name='ck_queue_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'resource_id', name='task_queue_kind_resource_id_key')
    )
    op.create_index('ix_queue_claim', 'task_queue', ['kind', 'state', 'available_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_time', 'audit_logs', ['created_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('csrf_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('datasources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('health_status', sa.Text(), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("kind IN ('postgres','mysql','doris')", name='datasources_kind_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'route', 'key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_roles_users', 'user_roles', ['role_id', 'user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name='agent_messages_role_check'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_session', 'agent_messages', ['session_id', 'created_at', 'id'], unique=False)
    op.create_table('analysis_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('checkpoint_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('policy_revision', sa.BigInteger(), nullable=False),
    sa.Column('final_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('CREATED','UNDERSTANDING','RETRIEVING','WAITING_INPUT','PLANNING','EXECUTING','OBSERVING','SYNTHESIZING','COMPLETED','PARTIAL','FAILED','CANCELLED')", name='ck_analysis_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['analysis_tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_owner_time', 'analysis_tasks', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_analysis_session', 'analysis_tasks', ['session_id', 'created_at'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_name', sa.Text(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=False),
    sa.Column('object_name', sa.Text(), nullable=False),
    sa.Column('datahub_urn', sa.Text(), nullable=True),
    sa.Column('object_type', sa.Text(), nullable=False),
    sa.Column('schema_hash', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahub_urn'),
    sa.UniqueConstraint('datasource_id', 'catalog_name', 'schema_name', 'object_name', name='datasets_datasource_id_catalog_name_schema_name_object_name_key')
    )
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('recipe_hash', sa.Text(), nullable=False),
    sa.Column('ingestion_version', sa.Text(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','LOST')", name='ingestion_tasks_status_check'),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestions_source', 'ingestion_tasks', ['datasource_id', 'created_at'], unique=False)
    op.create_table('saved_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependency_query_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('calculation','chart','evidence')", name='analysis_artifacts_kind_check'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_analysis', 'analysis_artifacts', ['analysis_id'], unique=False)
    op.create_table('analysis_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('observation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','SKIPPED')", name='ck_step_status'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'step_key', name='analysis_steps_analysis_id_step_key_key')
    )
    op.create_table('metadata_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_hash', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_dataset', 'metadata_snapshots', ['dataset_id', 'fetched_at'], unique=False)
    op.create_table('permission_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED','MOCK_APPROVED','REJECTED')", name='permission_requests_status_check'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.CheckConstraint("action IN ('discover','query')", name='permissions_action_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'dataset_id', 'action', name='permissions_key')
    )
    op.create_index('ix_permissions_dataset', 'permissions', ['dataset_id', 'role_id'], unique=False)
    op.create_table('query_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('original_sql', sa.Text(), nullable=False),
    sa.Column('validated_sql', sa.Text(), nullable=True),
    sa.Column('bound_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sql_hash', sa.Text(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_revision', sa.BigInteger(), nullable=False),
    sa.Column('provider_handle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('query','explain')", name='query_jobs_purpose_check'),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCEL_REQUESTED','CANCELLED','TIMED_OUT','LOST')", name='ck_query_status'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_tasks.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queries_analysis', 'query_jobs', ['analysis_id'], unique=False)
    op.create_index('ix_queries_owner_time', 'query_jobs', ['user_id', 'created_at'], unique=False)
    op.create_table('execution_leases',
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('datasource_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('fencing_token', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE','SUSPECT','RELEASED')", name='execution_leases_state_check'),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('ix_leases_source', 'execution_leases', ['datasource_id', 'state'], unique=False)
    op.create_index('ix_leases_user', 'execution_leases', ['user_id', 'state'], unique=False)
    op.create_table('query_dependencies',
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('metadata_snapshot_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['metadata_snapshot_id'], ['metadata_snapshots.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query_jobs.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'dataset_id')
    )
    op.create_index('ix_dependencies_dataset', 'query_dependencies', ['dataset_id', 'query_id'], unique=False)
    op.create_table('query_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_results_expiry', 'query_results', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_results_expiry', table_name='query_results')
    op.drop_table('query_results')
    op.drop_index('ix_dependencies_dataset', table_name='query_dependencies')
    op.drop_table('query_dependencies')
    op.drop_index('ix_leases_user', table_name='execution_leases')
    op.drop_index('ix_leases_source', table_name='execution_leases')
    op.drop_table('execution_leases')
    op.drop_index('ix_queries_owner_time', table_name='query_jobs')
    op.drop_index('ix_queries_analysis', table_name='query_jobs')
    op.drop_table('query_jobs')
    op.drop_index('ix_permissions_dataset', table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('permission_requests')
    op.drop_index('ix_snapshots_dataset', table_name='metadata_snapshots')
    op.drop_table('metadata_snapshots')
    op.drop_table('analysis_steps')
    op.drop_index('ix_artifacts_analysis', table_name='analysis_artifacts')
    op.drop_table('analysis_artifacts')
    op.drop_table('saved_queries')
    op.drop_index('ix_ingestions_source', table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    op.drop_table('datasets')
    op.drop_index('ix_analysis_session', table_name='analysis_tasks')
    op.drop_index('ix_analyses_owner_time', table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_index('ix_messages_session', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_roles_users', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('idempotency_keys')
    op.drop_table('datasources')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('agent_sessions')
    op.drop_table('users')
    op.drop_index('ix_queue_claim', table_name='task_queue')
    op.drop_table('task_queue')
    op.drop_index('ix_events_resource', table_name='task_events')
    op.drop_table('task_events')
    op.drop_table('roles')
    op.drop_table('policy_state')
    op.drop_table('metric_definitions')
    op.drop_table('execution_capacity')
    # ### end Alembic commands ###
